<?php

/*\
| | Project #2
| |
| | Each new term in the Fibonacci sequence is generated by adding the previous
| | two terms. By starting with 1 and 2, the first 10 terms will be:
| |
| | 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
| |
| | By considering the terms in the Fibonacci sequence whose values do not
| | exceed four million, find the sum of the even-valued terms.
\*/

$LIMIT = 4000000;
$fib = array(1, 2);
$sum = 2;

while($term < $LIMIT) {
    $term = next_fibonacci_term($fib);
    array_push($fib, $term);

    if(is_even($term)) { $sum += $term; }
}

print_r($fib);
echo "Sum: $sum\n";

function next_fibonacci_term($fib) {
    $a = count($fib);
    return ($fib[$a -1] + $fib[$a -2]);
}

function is_even($n) {
  if($n % 2 == 0) { return true; }
  return false;
}

?>